// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sorted_insert (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_bus_req_din,
        data_bus_req_full_n,
        data_bus_req_write,
        data_bus_rsp_empty_n,
        data_bus_rsp_read,
        data_bus_address,
        data_bus_datain,
        data_bus_dataout,
        data_bus_size,
        flist_req_din,
        flist_req_full_n,
        flist_req_write,
        flist_rsp_empty_n,
        flist_rsp_read,
        flist_address,
        flist_datain,
        flist_dataout,
        flist_size,
        next_free_location_read,
        queue,
        key,
        ap_return_0,
        ap_return_1
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b000000;
parameter    ap_ST_st2_fsm_1 = 6'b1;
parameter    ap_ST_st3_fsm_2 = 6'b10;
parameter    ap_ST_st4_fsm_3 = 6'b11;
parameter    ap_ST_st5_fsm_4 = 6'b100;
parameter    ap_ST_st6_fsm_5 = 6'b101;
parameter    ap_ST_st7_fsm_6 = 6'b110;
parameter    ap_ST_st8_fsm_7 = 6'b111;
parameter    ap_ST_st9_fsm_8 = 6'b1000;
parameter    ap_ST_st10_fsm_9 = 6'b1001;
parameter    ap_ST_st11_fsm_10 = 6'b1010;
parameter    ap_ST_st12_fsm_11 = 6'b1011;
parameter    ap_ST_st13_fsm_12 = 6'b1100;
parameter    ap_ST_st14_fsm_13 = 6'b1101;
parameter    ap_ST_st15_fsm_14 = 6'b1110;
parameter    ap_ST_st16_fsm_15 = 6'b1111;
parameter    ap_ST_st17_fsm_16 = 6'b10000;
parameter    ap_ST_st18_fsm_17 = 6'b10001;
parameter    ap_ST_st19_fsm_18 = 6'b10010;
parameter    ap_ST_st20_fsm_19 = 6'b10011;
parameter    ap_ST_st21_fsm_20 = 6'b10100;
parameter    ap_ST_st22_fsm_21 = 6'b10101;
parameter    ap_ST_st23_fsm_22 = 6'b10110;
parameter    ap_ST_st24_fsm_23 = 6'b10111;
parameter    ap_ST_st25_fsm_24 = 6'b11000;
parameter    ap_ST_st26_fsm_25 = 6'b11001;
parameter    ap_ST_st27_fsm_26 = 6'b11010;
parameter    ap_ST_st28_fsm_27 = 6'b11011;
parameter    ap_ST_st29_fsm_28 = 6'b11100;
parameter    ap_ST_st30_fsm_29 = 6'b11101;
parameter    ap_ST_st31_fsm_30 = 6'b11110;
parameter    ap_ST_st32_fsm_31 = 6'b11111;
parameter    ap_ST_st33_fsm_32 = 6'b100000;
parameter    ap_ST_st34_fsm_33 = 6'b100001;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   data_bus_req_din;
input   data_bus_req_full_n;
output   data_bus_req_write;
input   data_bus_rsp_empty_n;
output   data_bus_rsp_read;
output  [31:0] data_bus_address;
input  [63:0] data_bus_datain;
output  [63:0] data_bus_dataout;
output  [31:0] data_bus_size;
output   flist_req_din;
input   flist_req_full_n;
output   flist_req_write;
input   flist_rsp_empty_n;
output   flist_rsp_read;
output  [31:0] flist_address;
input  [31:0] flist_datain;
output  [31:0] flist_dataout;
output  [31:0] flist_size;
input  [31:0] next_free_location_read;
input  [31:0] queue;
input  [31:0] key;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_bus_req_din;
reg data_bus_req_write;
reg data_bus_rsp_read;
reg[31:0] data_bus_address;
reg[63:0] data_bus_dataout;
reg flist_req_write;
reg flist_rsp_read;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg   [5:0] ap_CS_fsm = 6'b000000;
reg   [63:0] reg_184;
reg    ap_sig_bdd_88;
reg   [31:0] data_bus_addr_reg_399;
reg   [31:0] flist_addr_read_reg_405;
wire   [63:0] data_bus_n_addr4748_part_set_fu_220_p3;
reg   [63:0] data_bus_n_addr4748_part_set_reg_429;
wire   [0:0] tmp_fu_228_p2;
reg   [0:0] tmp_reg_434;
reg   [31:0] data_bus_addr_1_reg_438;
reg   [63:0] data_bus_addr_1_read_1_reg_444;
reg   [31:0] l_rec_n_new_reg_449;
wire   [31:0] loop_k_fu_244_p1;
reg   [31:0] loop_k_reg_454;
wire   [0:0] demorgan_fu_259_p2;
reg   [0:0] demorgan_reg_461;
reg   [31:0] data_bus_addr_2_reg_465;
reg   [63:0] data_bus_addr_2_read_reg_471;
reg    ap_sig_bdd_145;
wire   [0:0] tmp5_fu_276_p2;
reg   [0:0] tmp5_reg_486;
wire   [0:0] tmp6_fu_309_p2;
reg    ap_sig_bdd_166;
reg   [31:0] data_bus_addr_3_reg_490;
wire   [63:0] data_bus_n_addr_33234_part_set_fu_303_p3;
reg   [63:0] data_bus_n_addr_33234_part_set_reg_495;
reg   [0:0] tmp6_reg_500;
reg   [31:0] data_bus_addr_4_reg_504;
wire   [63:0] data_bus_n_addr4344_part_set_fu_326_p3;
reg   [63:0] data_bus_n_addr4344_part_set_reg_510;
wire   [31:0] prev_k_fu_333_p1;
reg   [31:0] prev_k_reg_515;
wire   [63:0] data_bus_k_addr1819_part_set_fu_356_p5;
reg   [63:0] data_bus_k_addr1819_part_set_reg_521;
reg   [63:0] data_bus_k_addr_s_reg_107;
reg   [31:0] loop_n_reg_117;
reg   [63:0] loop_k_in_reg_127;
reg   [31:0] prev_1_reg_136;
reg   [31:0] prev_reg_147;
reg   [31:0] result_phi_fu_163_p8;
reg   [31:0] result_reg_160;
reg    ap_sig_bdd_216;
wire   [63:0] tmp5_i_fu_189_p1;
wire   [63:0] tmp1_fu_234_p1;
wire   [63:0] tmp4_fu_265_p1;
wire   [63:0] tmp7_fu_280_p1;
wire   [63:0] tmp8_fu_315_p1;
wire   [63:0] data_bus_k_addr2325_part_set_fu_207_p5;
wire   [63:0] data_bus_k_addr_389_part_set_fu_291_p5;
wire   [63:0] data_bus_k_addr_423_part_set_fu_337_p5;
wire   [63:0] data_bus_n_addr_42627_part_set_fu_349_p3;
wire   [63:0] data_bus_n_addr4546_part_set_fu_378_p3;
wire   [0:0] slt_fu_248_p2;
wire   [0:0] not_tmp_fu_253_p2;
reg   [31:0] ap_return_0_preg = 32'b00000000000000000000000000000000;
reg   [31:0] ap_return_1_preg = 32'b00000000000000000000000000000000;
reg   [5:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n == 1'b0) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_return_0_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_return_0_preg
    if (ap_rst_n == 1'b0) begin
        ap_return_0_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & ~ap_sig_bdd_216)) begin
            ap_return_0_preg <= result_phi_fu_163_p8;
        end
    end
end

/// ap_return_1_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_return_1_preg
    if (ap_rst_n == 1'b0) begin
        ap_return_1_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & ~ap_sig_bdd_216)) begin
            ap_return_1_preg <= flist_addr_read_reg_405;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((demorgan_reg_461 == ap_const_lv1_0) & ~ap_sig_bdd_145 & (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        data_bus_k_addr_s_reg_107 <= data_bus_datain;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        data_bus_k_addr_s_reg_107 <= data_bus_addr_1_read_1_reg_444;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((demorgan_reg_461 == ap_const_lv1_0) & ~ap_sig_bdd_145 & (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        loop_k_in_reg_127 <= data_bus_addr_2_read_reg_471;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        loop_k_in_reg_127 <= reg_184;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((demorgan_reg_461 == ap_const_lv1_0) & ~ap_sig_bdd_145 & (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        loop_n_reg_117 <= {{data_bus_datain[ap_const_lv32_3F : ap_const_lv32_20]}};
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        loop_n_reg_117 <= l_rec_n_new_reg_449;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((demorgan_reg_461 == ap_const_lv1_0) & ~ap_sig_bdd_145 & (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        prev_1_reg_136 <= loop_n_reg_117;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        prev_1_reg_136 <= queue;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((demorgan_reg_461 == ap_const_lv1_0) & ~ap_sig_bdd_145 & (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        prev_reg_147 <= prev_1_reg_136;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        prev_reg_147 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st34_fsm_33 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(tmp_fu_228_p2 == ap_const_lv1_0)))) begin
        result_reg_160 <= next_free_location_read;
    end else if (((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st21_fsm_20 == ap_CS_fsm)) | ((ap_ST_st33_fsm_32 == ap_CS_fsm) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500) & ~ap_sig_bdd_216))) begin
        result_reg_160 <= queue;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        data_bus_addr_1_read_1_reg_444 <= data_bus_datain;
        l_rec_n_new_reg_449 <= {{data_bus_datain[ap_const_lv32_3F : ap_const_lv32_20]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        data_bus_addr_1_reg_438 <= tmp1_fu_234_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((demorgan_reg_461 == ap_const_lv1_0) & (ap_ST_st16_fsm_15 == ap_CS_fsm) & ~ap_sig_bdd_145)) begin
        data_bus_addr_2_read_reg_471 <= data_bus_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & (demorgan_reg_461 == ap_const_lv1_0))) begin
        data_bus_addr_2_reg_465 <= tmp4_fu_265_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166)) begin
        data_bus_addr_3_reg_490 <= tmp7_fu_280_p1;
        data_bus_n_addr_33234_part_set_reg_495 <= data_bus_n_addr_33234_part_set_fu_303_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & (ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166)) begin
        data_bus_addr_4_reg_504 <= tmp8_fu_315_p1;
        data_bus_n_addr4344_part_set_reg_510 <= data_bus_n_addr4344_part_set_fu_326_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        data_bus_addr_reg_399 <= tmp5_i_fu_189_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st31_fsm_30 == ap_CS_fsm))) begin
        data_bus_k_addr1819_part_set_reg_521 <= data_bus_k_addr1819_part_set_fu_356_p5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st5_fsm_4 == ap_CS_fsm))) begin
        data_bus_n_addr4748_part_set_reg_429[0] <= data_bus_n_addr4748_part_set_fu_220_p3[0];
data_bus_n_addr4748_part_set_reg_429[1] <= data_bus_n_addr4748_part_set_fu_220_p3[1];
data_bus_n_addr4748_part_set_reg_429[2] <= data_bus_n_addr4748_part_set_fu_220_p3[2];
data_bus_n_addr4748_part_set_reg_429[3] <= data_bus_n_addr4748_part_set_fu_220_p3[3];
data_bus_n_addr4748_part_set_reg_429[4] <= data_bus_n_addr4748_part_set_fu_220_p3[4];
data_bus_n_addr4748_part_set_reg_429[5] <= data_bus_n_addr4748_part_set_fu_220_p3[5];
data_bus_n_addr4748_part_set_reg_429[6] <= data_bus_n_addr4748_part_set_fu_220_p3[6];
data_bus_n_addr4748_part_set_reg_429[7] <= data_bus_n_addr4748_part_set_fu_220_p3[7];
data_bus_n_addr4748_part_set_reg_429[8] <= data_bus_n_addr4748_part_set_fu_220_p3[8];
data_bus_n_addr4748_part_set_reg_429[9] <= data_bus_n_addr4748_part_set_fu_220_p3[9];
data_bus_n_addr4748_part_set_reg_429[10] <= data_bus_n_addr4748_part_set_fu_220_p3[10];
data_bus_n_addr4748_part_set_reg_429[11] <= data_bus_n_addr4748_part_set_fu_220_p3[11];
data_bus_n_addr4748_part_set_reg_429[12] <= data_bus_n_addr4748_part_set_fu_220_p3[12];
data_bus_n_addr4748_part_set_reg_429[13] <= data_bus_n_addr4748_part_set_fu_220_p3[13];
data_bus_n_addr4748_part_set_reg_429[14] <= data_bus_n_addr4748_part_set_fu_220_p3[14];
data_bus_n_addr4748_part_set_reg_429[15] <= data_bus_n_addr4748_part_set_fu_220_p3[15];
data_bus_n_addr4748_part_set_reg_429[16] <= data_bus_n_addr4748_part_set_fu_220_p3[16];
data_bus_n_addr4748_part_set_reg_429[17] <= data_bus_n_addr4748_part_set_fu_220_p3[17];
data_bus_n_addr4748_part_set_reg_429[18] <= data_bus_n_addr4748_part_set_fu_220_p3[18];
data_bus_n_addr4748_part_set_reg_429[19] <= data_bus_n_addr4748_part_set_fu_220_p3[19];
data_bus_n_addr4748_part_set_reg_429[20] <= data_bus_n_addr4748_part_set_fu_220_p3[20];
data_bus_n_addr4748_part_set_reg_429[21] <= data_bus_n_addr4748_part_set_fu_220_p3[21];
data_bus_n_addr4748_part_set_reg_429[22] <= data_bus_n_addr4748_part_set_fu_220_p3[22];
data_bus_n_addr4748_part_set_reg_429[23] <= data_bus_n_addr4748_part_set_fu_220_p3[23];
data_bus_n_addr4748_part_set_reg_429[24] <= data_bus_n_addr4748_part_set_fu_220_p3[24];
data_bus_n_addr4748_part_set_reg_429[25] <= data_bus_n_addr4748_part_set_fu_220_p3[25];
data_bus_n_addr4748_part_set_reg_429[26] <= data_bus_n_addr4748_part_set_fu_220_p3[26];
data_bus_n_addr4748_part_set_reg_429[27] <= data_bus_n_addr4748_part_set_fu_220_p3[27];
data_bus_n_addr4748_part_set_reg_429[28] <= data_bus_n_addr4748_part_set_fu_220_p3[28];
data_bus_n_addr4748_part_set_reg_429[29] <= data_bus_n_addr4748_part_set_fu_220_p3[29];
data_bus_n_addr4748_part_set_reg_429[30] <= data_bus_n_addr4748_part_set_fu_220_p3[30];
data_bus_n_addr4748_part_set_reg_429[31] <= data_bus_n_addr4748_part_set_fu_220_p3[31];
        tmp_reg_434 <= tmp_fu_228_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        demorgan_reg_461 <= demorgan_fu_259_p2;
        loop_k_reg_454 <= loop_k_fu_244_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_88)) begin
        flist_addr_read_reg_405 <= flist_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st23_fsm_22 == ap_CS_fsm))) begin
        prev_k_reg_515 <= prev_k_fu_333_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_88) | ((ap_ST_st8_fsm_7 == ap_CS_fsm) & ~(data_bus_rsp_empty_n == ap_const_logic_0)) | (~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st26_fsm_25 == ap_CS_fsm)))) begin
        reg_184 <= data_bus_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~ap_sig_bdd_166)) begin
        tmp5_reg_486 <= tmp5_fu_276_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166)) begin
        tmp6_reg_500 <= tmp6_fu_309_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or ap_sig_bdd_216)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st33_fsm_32 == ap_CS_fsm) & ~ap_sig_bdd_216))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_216)
begin
    if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & ~ap_sig_bdd_216)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_return_0 assign process. ///
always @ (ap_CS_fsm or result_phi_fu_163_p8 or ap_sig_bdd_216 or ap_return_0_preg)
begin
    if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & ~ap_sig_bdd_216)) begin
        ap_return_0 = result_phi_fu_163_p8;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

/// ap_return_1 assign process. ///
always @ (ap_CS_fsm or flist_addr_read_reg_405 or ap_sig_bdd_216 or ap_return_1_preg)
begin
    if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & ~ap_sig_bdd_216)) begin
        ap_return_1 = flist_addr_read_reg_405;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

/// data_bus_address assign process. ///
always @ (ap_start or ap_CS_fsm or data_bus_req_full_n or data_bus_addr_reg_399 or tmp_reg_434 or data_bus_addr_1_reg_438 or demorgan_reg_461 or data_bus_addr_2_reg_465 or tmp5_fu_276_p2 or tmp5_reg_486 or tmp6_fu_309_p2 or ap_sig_bdd_166 or data_bus_addr_3_reg_490 or tmp6_reg_500 or data_bus_addr_4_reg_504 or ap_sig_bdd_216 or tmp5_i_fu_189_p1 or tmp1_fu_234_p1 or tmp4_fu_265_p1 or tmp7_fu_280_p1 or tmp8_fu_315_p1)
begin
    if (((ap_ST_st24_fsm_23 == ap_CS_fsm) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st27_fsm_26 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st28_fsm_27 == ap_CS_fsm)))) begin
        data_bus_address = data_bus_addr_4_reg_504;
    end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st21_fsm_20 == ap_CS_fsm))) begin
        data_bus_address = data_bus_addr_3_reg_490;
    end else if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & (ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166)) begin
        data_bus_address = tmp8_fu_315_p1;
    end else if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166)) begin
        data_bus_address = tmp7_fu_280_p1;
    end else if (((demorgan_reg_461 == ap_const_lv1_0) & (ap_ST_st17_fsm_16 == ap_CS_fsm))) begin
        data_bus_address = data_bus_addr_2_reg_465;
    end else if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & (demorgan_reg_461 == ap_const_lv1_0))) begin
        data_bus_address = tmp4_fu_265_p1;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        data_bus_address = data_bus_addr_1_reg_438;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        data_bus_address = tmp1_fu_234_p1;
    end else if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(data_bus_req_full_n == ap_const_logic_0)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st5_fsm_4 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st34_fsm_33 == ap_CS_fsm)) | ((ap_ST_st33_fsm_32 == ap_CS_fsm) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500) & ~ap_sig_bdd_216) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~(ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st32_fsm_31 == ap_CS_fsm)))) begin
        data_bus_address = data_bus_addr_reg_399;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        data_bus_address = tmp5_i_fu_189_p1;
    end else begin
        data_bus_address = 'bx;
    end
end

/// data_bus_dataout assign process. ///
always @ (ap_CS_fsm or data_bus_req_full_n or data_bus_n_addr4748_part_set_fu_220_p3 or data_bus_n_addr4748_part_set_reg_429 or tmp_reg_434 or tmp5_fu_276_p2 or tmp5_reg_486 or tmp6_fu_309_p2 or ap_sig_bdd_166 or data_bus_n_addr_33234_part_set_reg_495 or tmp6_reg_500 or data_bus_n_addr4344_part_set_reg_510 or data_bus_k_addr1819_part_set_reg_521 or ap_sig_bdd_216 or data_bus_k_addr2325_part_set_fu_207_p5 or data_bus_k_addr_389_part_set_fu_291_p5 or data_bus_k_addr_423_part_set_fu_337_p5 or data_bus_n_addr_42627_part_set_fu_349_p3 or data_bus_n_addr4546_part_set_fu_378_p3)
begin
    if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st34_fsm_33 == ap_CS_fsm))) begin
        data_bus_dataout = data_bus_n_addr4546_part_set_fu_378_p3;
    end else if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500) & ~ap_sig_bdd_216)) begin
        data_bus_dataout = data_bus_n_addr4344_part_set_reg_510;
    end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st32_fsm_31 == ap_CS_fsm))) begin
        data_bus_dataout = data_bus_k_addr1819_part_set_reg_521;
    end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st28_fsm_27 == ap_CS_fsm))) begin
        data_bus_dataout = data_bus_n_addr_42627_part_set_fu_349_p3;
    end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st27_fsm_26 == ap_CS_fsm))) begin
        data_bus_dataout = data_bus_k_addr_423_part_set_fu_337_p5;
    end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st21_fsm_20 == ap_CS_fsm))) begin
        data_bus_dataout = data_bus_n_addr_33234_part_set_reg_495;
    end else if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~(ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166)) begin
        data_bus_dataout = data_bus_n_addr4748_part_set_reg_429;
    end else if (((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166)) begin
        data_bus_dataout = data_bus_k_addr_389_part_set_fu_291_p5;
    end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st5_fsm_4 == ap_CS_fsm))) begin
        data_bus_dataout = data_bus_n_addr4748_part_set_fu_220_p3;
    end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(data_bus_req_full_n == ap_const_logic_0))) begin
        data_bus_dataout = data_bus_k_addr2325_part_set_fu_207_p5;
    end else begin
        data_bus_dataout = 'bx;
    end
end

/// data_bus_req_din assign process. ///
always @ (ap_start or ap_CS_fsm or data_bus_req_full_n or tmp_reg_434 or demorgan_reg_461 or tmp5_fu_276_p2 or tmp5_reg_486 or tmp6_fu_309_p2 or ap_sig_bdd_166 or tmp6_reg_500 or ap_sig_bdd_216)
begin
    if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(data_bus_req_full_n == ap_const_logic_0)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st5_fsm_4 == ap_CS_fsm)) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st21_fsm_20 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st34_fsm_33 == ap_CS_fsm)) | ((ap_ST_st33_fsm_32 == ap_CS_fsm) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500) & ~ap_sig_bdd_216) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~(ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st27_fsm_26 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st28_fsm_27 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st32_fsm_31 == ap_CS_fsm)))) begin
        data_bus_req_din = ap_const_logic_1;
    end else if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0)) | (ap_ST_st6_fsm_5 == ap_CS_fsm) | ((ap_ST_st14_fsm_13 == ap_CS_fsm) & (demorgan_reg_461 == ap_const_lv1_0)) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & (ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | ((demorgan_reg_461 == ap_const_lv1_0) & (ap_ST_st17_fsm_16 == ap_CS_fsm)) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm))) begin
        data_bus_req_din = ap_const_logic_0;
    end else begin
        data_bus_req_din = ap_const_logic_0;
    end
end

/// data_bus_req_write assign process. ///
always @ (ap_start or ap_CS_fsm or data_bus_req_full_n or tmp_reg_434 or demorgan_reg_461 or tmp5_fu_276_p2 or tmp5_reg_486 or tmp6_fu_309_p2 or ap_sig_bdd_166 or tmp6_reg_500 or ap_sig_bdd_216)
begin
    if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(data_bus_req_full_n == ap_const_logic_0)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st5_fsm_4 == ap_CS_fsm)) | (ap_ST_st6_fsm_5 == ap_CS_fsm) | ((ap_ST_st14_fsm_13 == ap_CS_fsm) & (demorgan_reg_461 == ap_const_lv1_0)) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & (ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & (ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st21_fsm_20 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st34_fsm_33 == ap_CS_fsm)) | ((ap_ST_st33_fsm_32 == ap_CS_fsm) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500) & ~ap_sig_bdd_216) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | ((demorgan_reg_461 == ap_const_lv1_0) & (ap_ST_st17_fsm_16 == ap_CS_fsm)) | ((ap_ST_st20_fsm_19 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~(ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st27_fsm_26 == ap_CS_fsm)) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st28_fsm_27 == ap_CS_fsm)) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (~(data_bus_req_full_n == ap_const_logic_0) & (ap_ST_st32_fsm_31 == ap_CS_fsm)))) begin
        data_bus_req_write = ap_const_logic_1;
    end else begin
        data_bus_req_write = ap_const_logic_0;
    end
end

/// data_bus_rsp_read assign process. ///
always @ (ap_CS_fsm or data_bus_rsp_empty_n or ap_sig_bdd_88 or demorgan_reg_461 or ap_sig_bdd_145)
begin
    if ((((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_88) | ((ap_ST_st8_fsm_7 == ap_CS_fsm) & ~(data_bus_rsp_empty_n == ap_const_logic_0)) | (~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st26_fsm_25 == ap_CS_fsm)) | (~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st11_fsm_10 == ap_CS_fsm)) | ((demorgan_reg_461 == ap_const_lv1_0) & (ap_ST_st16_fsm_15 == ap_CS_fsm) & ~ap_sig_bdd_145) | ((demorgan_reg_461 == ap_const_lv1_0) & ~ap_sig_bdd_145 & (ap_ST_st19_fsm_18 == ap_CS_fsm)) | (~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st23_fsm_22 == ap_CS_fsm)) | (~(data_bus_rsp_empty_n == ap_const_logic_0) & (ap_ST_st31_fsm_30 == ap_CS_fsm)))) begin
        data_bus_rsp_read = ap_const_logic_1;
    end else begin
        data_bus_rsp_read = ap_const_logic_0;
    end
end

/// flist_req_write assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        flist_req_write = ap_const_logic_1;
    end else begin
        flist_req_write = ap_const_logic_0;
    end
end

/// flist_rsp_read assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_88)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~ap_sig_bdd_88)) begin
        flist_rsp_read = ap_const_logic_1;
    end else begin
        flist_rsp_read = ap_const_logic_0;
    end
end

/// result_phi_fu_163_p8 assign process. ///
always @ (ap_CS_fsm or queue or tmp_reg_434 or tmp5_reg_486 or tmp6_reg_500 or result_reg_160)
begin
    if (((ap_ST_st33_fsm_32 == ap_CS_fsm) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500))) begin
        result_phi_fu_163_p8 = queue;
    end else begin
        result_phi_fu_163_p8 = result_reg_160;
    end
end
always @ (ap_start or ap_CS_fsm or data_bus_req_full_n or data_bus_rsp_empty_n or ap_sig_bdd_88 or tmp_fu_228_p2 or demorgan_fu_259_p2 or ap_sig_bdd_145 or tmp5_fu_276_p2 or tmp6_fu_309_p2 or ap_sig_bdd_166 or ap_sig_bdd_216)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st3_fsm_2 : 
            if (~ap_sig_bdd_88) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st4_fsm_3 : 
            if (~(data_bus_req_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        ap_ST_st5_fsm_4 : 
            if ((~(data_bus_req_full_n == ap_const_logic_0) & ~(tmp_fu_228_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end else if ((~(data_bus_req_full_n == ap_const_logic_0) & (tmp_fu_228_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            if (~(data_bus_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            if (~(data_bus_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            if ((demorgan_fu_259_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            if (~ap_sig_bdd_145) begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end
        ap_ST_st17_fsm_16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        ap_ST_st18_fsm_17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
        ap_ST_st19_fsm_18 : 
            if (~ap_sig_bdd_145) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end
        ap_ST_st20_fsm_19 : 
            if ((~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~(ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166)) begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end else if ((~(ap_const_lv1_0 == tmp5_fu_276_p2) & (ap_const_lv1_0 == tmp6_fu_309_p2) & ~ap_sig_bdd_166)) begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end else if (((ap_const_lv1_0 == tmp5_fu_276_p2) & ~ap_sig_bdd_166)) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        ap_ST_st21_fsm_20 : 
            if (~(data_bus_req_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end else begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end
        ap_ST_st22_fsm_21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
        ap_ST_st23_fsm_22 : 
            if (~(data_bus_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st24_fsm_23;
            end else begin
                ap_NS_fsm = ap_ST_st23_fsm_22;
            end
        ap_ST_st24_fsm_23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        ap_ST_st26_fsm_25 : 
            if (~(data_bus_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end else begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end
        ap_ST_st27_fsm_26 : 
            if (~(data_bus_req_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end else begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end
        ap_ST_st28_fsm_27 : 
            if (~(data_bus_req_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st29_fsm_28;
            end else begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end
        ap_ST_st29_fsm_28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
        ap_ST_st30_fsm_29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
        ap_ST_st31_fsm_30 : 
            if (~(data_bus_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st32_fsm_31;
            end else begin
                ap_NS_fsm = ap_ST_st31_fsm_30;
            end
        ap_ST_st32_fsm_31 : 
            if (~(data_bus_req_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end else begin
                ap_NS_fsm = ap_ST_st32_fsm_31;
            end
        ap_ST_st33_fsm_32 : 
            if (~ap_sig_bdd_216) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end
        ap_ST_st34_fsm_33 : 
            if (~(data_bus_req_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end else begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_145 assign process. ///
always @ (data_bus_rsp_empty_n or demorgan_reg_461)
begin
    ap_sig_bdd_145 = ((data_bus_rsp_empty_n == ap_const_logic_0) & (demorgan_reg_461 == ap_const_lv1_0));
end

/// ap_sig_bdd_166 assign process. ///
always @ (data_bus_req_full_n or tmp5_fu_276_p2 or tmp6_fu_309_p2)
begin
    ap_sig_bdd_166 = (((data_bus_req_full_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp5_fu_276_p2)) | ((data_bus_req_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp5_fu_276_p2) & ~(ap_const_lv1_0 == tmp6_fu_309_p2)));
end

/// ap_sig_bdd_216 assign process. ///
always @ (data_bus_req_full_n or tmp_reg_434 or tmp5_reg_486 or tmp6_reg_500)
begin
    ap_sig_bdd_216 = ((data_bus_req_full_n == ap_const_logic_0) & (tmp_reg_434 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp5_reg_486) & (ap_const_lv1_0 == tmp6_reg_500));
end

/// ap_sig_bdd_88 assign process. ///
always @ (data_bus_rsp_empty_n or flist_rsp_empty_n)
begin
    ap_sig_bdd_88 = ((flist_rsp_empty_n == ap_const_logic_0) | (data_bus_rsp_empty_n == ap_const_logic_0));
end
assign data_bus_k_addr1819_part_set_fu_356_p5 = {{data_bus_datain[32'd63 : 32'd32]}, {key}};
assign data_bus_k_addr2325_part_set_fu_207_p5 = {{reg_184[32'd63 : 32'd32]}, {key}};
assign data_bus_k_addr_389_part_set_fu_291_p5 = {{data_bus_k_addr_s_reg_107[32'd63 : 32'd32]}, {loop_k_reg_454}};
assign data_bus_k_addr_423_part_set_fu_337_p5 = {{reg_184[32'd63 : 32'd32]}, {prev_k_reg_515}};
assign data_bus_n_addr4344_part_set_fu_326_p3 = {{prev_1_reg_136}, {key}};
assign data_bus_n_addr4546_part_set_fu_378_p3 = {{queue}, {key}};
assign data_bus_n_addr4748_part_set_fu_220_p3 = {{ap_const_lv32_0}, {key}};
assign data_bus_n_addr_33234_part_set_fu_303_p3 = {{next_free_location_read}, {loop_k_reg_454}};
assign data_bus_n_addr_42627_part_set_fu_349_p3 = {{next_free_location_read}, {prev_k_reg_515}};
assign data_bus_size = ap_const_lv32_1;
assign demorgan_fu_259_p2 = (slt_fu_248_p2 | not_tmp_fu_253_p2);
assign flist_address = tmp5_i_fu_189_p1;
assign flist_dataout = ap_const_lv32_0;
assign flist_req_din = ap_const_logic_0;
assign flist_size = ap_const_lv32_1;
assign loop_k_fu_244_p1 = loop_k_in_reg_127[31:0];
assign not_tmp_fu_253_p2 = (loop_n_reg_117 == ap_const_lv32_0? 1'b1: 1'b0);
assign prev_k_fu_333_p1 = data_bus_datain[31:0];
assign slt_fu_248_p2 = ($signed(key) < $signed(loop_k_fu_244_p1)? 1'b1: 1'b0);
assign tmp1_fu_234_p1 = $unsigned(queue);
assign tmp4_fu_265_p1 = $unsigned(loop_n_reg_117);
assign tmp5_fu_276_p2 = ($signed(loop_k_reg_454) > $signed(key)? 1'b1: 1'b0);
assign tmp5_i_fu_189_p1 = $unsigned(next_free_location_read);
assign tmp6_fu_309_p2 = (prev_reg_147 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp7_fu_280_p1 = $unsigned(prev_1_reg_136);
assign tmp8_fu_315_p1 = $unsigned(prev_reg_147);
assign tmp_fu_228_p2 = (queue == ap_const_lv32_0? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    data_bus_n_addr4748_part_set_reg_429[63:32] <= 32'b00000000000000000000000000000000;
end



endmodule //sorted_insert

